[build]
  command = "npm run build"
  publish = "dist" # or "build" for CRA

[[redirects]]
  from = "/api/*"
  to = "https://project-hotel-bookings-3.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://app-like-hotel-booking.netlify.app"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
